OrganizationTags = [
    {name: "Counseling"},
    {name: "Refugee"},
    {name: "Tutoring/Literacy"},
    {name: "Before/After School"},
    {name: "Career-Services"},
    {name: "Summer Programs"},
    {name: "Human Trafficking"},
    {name: "Food Pantry/Soup Kitchen"},
    {name: "Medical Aid"},
    {name: "Clothing"},
    {name: "Shelter/Safety"},
    {name: "Low Income Housing/Financial Services"},
    {name: "Legal Services"},
];
